# for macos
# docker build --platform linux/amd64 -t ubuntu_openwrt .
# run
# docker run --platform linux/amd64 -it docker.io/library/ubuntu_openwrt

FROM ubuntu:rolling

# choose version
ENV version=v22.03.5

# install package
RUN apt update && apt full-upgrade -y &&\
	apt install -y build-essential clang flex bison g++ gawk\
	gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev\
	python3-distutils rsync unzip zlib1g-dev file wget

# clone git and install
RUN	cd ~ &&\
	git clone https://git.openwrt.org/openwrt/openwrt.git &&\
	cd openwrt &&\
	git checkout $version &&\
	./scripts/feeds update -a && ./scripts/feeds install -a

# echo install.sh
RUN echo 'cd ~/openwrt &&\
	make menuconfig && make -j$(nproc) kernel_menuconfig &&\
	make -j$(nproc) defconfig download clean world'\
	> ~/setup.sh

CMD sh ~/setup.sh
